Creates and reads to file

diff --git a/sample/testDataA7/BroadTests/runExamples b/sample/testDataA7/BroadTests/runExamples
--- a/sample/testDataA7/BroadTests/runExamples
+++ b/sample/testDataA7/BroadTests/runExamples
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 # file.c-  file to compile
 # file.in  file of commands to tm to run code
 # file.expected file of expected output
@@ -8,39 +8,68 @@
 
 diffExpectedMem_flag=false
 printTm_flag=false
+printMyTm_flag=false
 printExpectedOutput_flag=false
+printSourceCode_flag=false
 fileIn=''
 
 compiler=../../../c-
 tmp=ztmp$$.txt
 
-while getopts 'ef:mt' flag; do
+while getopts 'cef:hmtT' flag; do
     case "${flag}" in
+    c) printSourceCode_flag=true ;;
     e) printExpectedOutput_flag=true ;;
     f) fileIn="${OPTARG}" ;;
-    t) printTm_flag=true ;;
+    h) printHelp_flag=true ;;
     m) diffExpectedMem_flag=true ;;
+    t) printTm_flag=true ;;
+    T) printMyTm_flag=true ;;
+    *) echo "Invalid flag '-${flag}'"
     esac
 done
 
-if [ -f $fileIn ]; then
+if [ "$printHelp_flag" = true ]; then
+    echo "Usage: runExamples [options]"
+    echo "-----------------------------"
+    echo "Options:"
+    echo "---------"
+    echo "-c) Print Source Code"
+    echo "-e) Print Expected Output"
+    echo "-f <fileName>) Specify file for tests."
+    echo "-h) Print this help message"
+    echo "-m) Compare exptected mem to your mem"
+    echo "-t) Print example .tm.bpk file"
+    echo "-T) Print MY .tm file"
+    exit 1
+fi
+
+if [ -f "$fileIn" ]; then
     skipActualChecking=false
-    file=`basename $fileIn '.c-'`
-    if [ $printExpectedOutput_flag == true ]; then
-        cat $file.expected
+    file=$(basename "$fileIn" '.c-')
+    if [ "$printExpectedOutput_flag" = true ]; then
+        cat "$file.expected"
         skipActualChecking=true
     fi
-    if [ $diffExpectedMem_flag == true ]; then
-        $compiler $file.c- -M > tmp1.txt
-        sdiff -l -s tmp1.txt $file.mem
+    if [ "$diffExpectedMem_flag" = true ]; then
+        $compiler "$file.c-" -M > tmp1.txt
+        sdiff -l -s tmp1.txt "$file.mem"
         rm tmp1.txt
         skipActualChecking=true
     fi
-    if [ $printTm_flag == true ]; then
-        cat $file.tm.bkp
+    if [ "$printSourceCode_flag" = true ]; then
+        cat "$file.c-"
         skipActualChecking=true
     fi
-    if [ $skipActualChecking == true ]; then
+    if [ "$printTm_flag" = true ]; then
+        cat "$file.tm.bkp"
+        skipActualChecking=true
+    fi
+    if [ "$printMyTm_flag" = true ]; then
+        cat "$file.tm"
+        skipActualChecking=true
+    fi
+    if [ "$skipActualChecking" = true ]; then
         exit 1
     fi
 fi
@@ -51,7 +80,7 @@ if [ -f $fileIn ]
     file=$fileIn
     echo "===================================="
     echo "FILE: $file"
-	file=`basename $file '.c-'`
+	file=$(basename $file '.c-')
         rm -f $file.tm $file.out
         $compiler  $file.c- > $file.out
         $compiler -M $file.c- > $file.mem
@@ -107,7 +136,7 @@ else
     do
         echo "===================================="
         echo "FILE: $file"
-        file=`basename $file '.c-'`
+        file=$(basename $file '.c-')
             rm -f $file.tm $file.out
             $compiler  $file.c- > $file.out
             $compiler -M $file.c- > $file.mem
